# generated by terraform template, do not change manually

[masters]
%{ for node in master_nodes ~}
${node.name} ansible_host=${node.ip} ansible_user=${ansible_user} vm_id=${node.vm_id}
%{ endfor ~}

[workers]
%{ for node in worker_nodes ~}
${node.name} ansible_host=${node.ip} ansible_user=${ansible_user} vm_id=${node.vm_id}
%{ endfor ~}

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_ssh_private_key_file=${ssh_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=False

